"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

/**
 * Generated by scripts/build-intro-sprite.py from public/intro.png.
 *
 * A uniform grid, so frames are addressed with percentage background
 * positions and no pixel size is ever hardcoded — the sprite scales to
 * whatever box it's given.
 */
export const SPRITE_SHEET = {
  src: "/intro-sprite.webp",
  cols: 6,
  rows: 6,
  /** width / height of a single cell */
  frameAspect: 1.2439,
};

const TOTAL_FRAMES = SPRITE_SHEET.cols * SPRITE_SHEET.rows;

function framePosition(index: number) {
  const { cols, rows } = SPRITE_SHEET;
  const col = index % cols;
  const row = Math.floor(index / cols);
  return {
    backgroundPositionX: cols > 1 ? `${(col / (cols - 1)) * 100}%` : "0%",
    backgroundPositionY: rows > 1 ? `${(row / (rows - 1)) * 100}%` : "0%",
  };
}

export interface SpriteAvatarProps {
  /** Frames per second. */
  fps?: number;
  className?: string;
  /** Description for assistive tech. */
  label?: string;
  /** Shown until the sheet loads, and kept if it never does. */
  fallbackSrc?: string;
}

export function SpriteAvatar({
  fps = 7,
  className,
  label = "Illustration of Aakrit working at his desk",
  fallbackSrc = "/aakrit.jpg",
}: SpriteAvatarProps) {
  const [frame, setFrame] = React.useState(0);
  const [active, setActive] = React.useState(true);
  const [reduced, setReduced] = React.useState(false);
  const [sheet, setSheet] = React.useState<"loading" | "ready" | "missing">(
    "loading"
  );

  const hostRef = React.useRef<HTMLDivElement>(null);

  // A missing sheet would otherwise render as an invisible box that silently
  // reserves space, so probe it and fall back to the photo if it isn't there.
  React.useEffect(() => {
    const probe = new window.Image();
    probe.onload = () => setSheet("ready");
    probe.onerror = () => {
      setSheet("missing");
      if (process.env.NODE_ENV !== "production") {
        console.warn(
          `[SpriteAvatar] Could not load "${SPRITE_SHEET.src}". ` +
            `Run: python3 scripts/build-intro-sprite.py`
        );
      }
    };
    probe.src = SPRITE_SHEET.src;
    return () => {
      probe.onload = null;
      probe.onerror = null;
    };
  }, []);

  // Honour the OS "reduce motion" setting — hold on a single frame instead.
  React.useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const sync = () => setReduced(mq.matches);
    sync();
    mq.addEventListener("change", sync);
    return () => mq.removeEventListener("change", sync);
  }, []);

  // Don't burn frames while scrolled away or on a background tab.
  React.useEffect(() => {
    const el = hostRef.current;
    if (!el) return;

    let onScreen = true;
    const update = () => setActive(onScreen && !document.hidden);

    const io = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting;
        update();
      },
      { rootMargin: "128px" }
    );
    io.observe(el);
    document.addEventListener("visibilitychange", update);

    return () => {
      io.disconnect();
      document.removeEventListener("visibilitychange", update);
    };
  }, []);

  React.useEffect(() => {
    if (sheet !== "ready" || reduced || !active) return;
    const id = window.setInterval(
      () => setFrame((prev) => (prev + 1) % TOTAL_FRAMES),
      1000 / fps
    );
    return () => window.clearInterval(id);
  }, [sheet, reduced, active, fps]);

  if (sheet !== "ready") {
    return (
      <div
        ref={hostRef}
        className={cn("overflow-hidden rounded-full bg-muted", className)}
        style={{ aspectRatio: String(SPRITE_SHEET.frameAspect) }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={fallbackSrc}
          alt={label}
          className={cn(
            "h-full w-full object-cover transition-opacity duration-300",
            sheet === "loading" ? "opacity-0" : "opacity-100"
          )}
        />
      </div>
    );
  }

  return (
    <div
      ref={hostRef}
      role="img"
      aria-label={label}
      className={cn("bg-no-repeat", className)}
      style={{
        backgroundImage: `url(${SPRITE_SHEET.src})`,
        backgroundSize: `${SPRITE_SHEET.cols * 100}% ${SPRITE_SHEET.rows * 100}%`,
        aspectRatio: String(SPRITE_SHEET.frameAspect),
        ...framePosition(reduced ? 0 : frame),
      }}
    />
  );
}

export default SpriteAvatar;
